### ISSUE TITLE
Can't quit neovim's floating window under a mouse click

### ISSUE THREAD

**Issue by kdurant** [liuchengxu/vim-which-key#41] opened 2019-03-15 00:41 UTC
If use mouse click other region when had float windows, can't quit float window

**Comment by liuchengxu** [comment] 2019-03-15 00:54
I don't have a mouse, so can't help here. But I've add an option for not using the floating window, you can add `let g:which_key_use_floating_win = 0` in your vimrc to fall back to the old way.

**Comment by free-easy** [comment] 2019-03-15 14:08
With `let g:which_key_use_floating_win = 0`, the menu doesn't close anymore.
I'm using neovim 4.0.

**Comment by liuchengxu** [comment] 2019-03-15 15:17
@free-easy fixed by https://github.com/liuchengxu/vim-which-key/commit/dac639995d0629cfcf5bd823c6d50645e3ad9c75, please pull the latest commit.

**Comment by free-easy** [comment] 2019-03-15 17:31
I confirm that it's fixed.

**Comment by liuchengxu** [comment] 2019-12-25 07:49
I have a mouse now and I can't reproduce this issue. Feel free to reopen if you can reproduce it with a minimal vimrc.

**Closed by liuchengxu** 2019-12-25 07:49 UTC
Labels: haven't tried yet
