### ISSUE TITLE
Don't display group names

### ISSUE THREAD

**Issue by kdurant** [liuchengxu/vim-which-key#17] opened 2018-09-27 08:31 UTC
- OS: Win10

- Vim: neovim0.3.0

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
nnoremap <silent> <space> :WhichKey '<Space>'<CR>
set timeoutlen=500
autocmd! FileType which_key
autocmd  FileType which_key set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
let g:which_key_map.f = { 'name' : '+file' }
```

### Problem Description
Don't display group names "file"

**Comment by liuchengxu** [comment] 2018-09-27 09:03
Please provide a clearer description and a minimal vimrc if you think it's a bug.

**Comment by kdurant** [comment] 2018-09-27 09:04
![qq 20180927170347](https://user-images.githubusercontent.com/2704364/46135257-54899680-c277-11e8-972f-01ff94eac2db.png)
按照上面的设置后，是应该显示group names的，但这里没有显示（“file”）

**Comment by liuchengxu** [comment] 2018-09-27 09:07
I need a mininal vimrc to reproduce.

**Comment by kdurant** [comment] 2018-09-28 00:52
算了，弄个最小配置太麻烦了。凑合用吧

**Comment by mortang2410** [comment] 2018-10-04 06:52
This shouldn't be closed. I too have the same problem: no group names are displayed right now and the plugin is currently broken.

**Comment by kdurant** [comment] 2018-10-04 07:45
@mortang2410 Can you provide a mininal vimrc to reproduce？

**Comment by liuchengxu** [comment] 2018-10-04 08:37
This plugin works well in my case. If you run into any issue, please provide a minimal vimrc and exact steps to reproduce, otherwise I can do nothing about it.

**Comment by mortang2410** [comment] 2018-10-05 03:34
Minimal .vimrc
```
let mapleader = "\<Space>"

call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-which-key'

call plug#end()

set timeoutlen=500
let g:which_key_map =  {}
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
let g:which_key_map.w = {
      \ 'name' : 'windows' ,
      \ 'w' : ['<C-W>w'     , 'other-window']          ,
      \ 'd' : ['<C-W>c'     , 'delete-window']         ,
      \ '-' : ['<C-W>s'     , 'split-window-below']    ,
      \ '|' : ['<C-W>v'     , 'split-window-right']    ,
      \ '2' : ['<C-W>v'     , 'layout-double-columns'] ,
      \ 'h' : ['<C-W>h'     , 'window-left']           ,
      \ 'j' : ['<C-W>j'     , 'window-below']          ,
      \ 'l' : ['<C-W>l'     , 'window-right']          ,
      \ 'k' : ['<C-W>k'     , 'window-up']             ,
      \ 'H' : ['<C-W>5<'    , 'expand-window-left']    ,
      \ 'J' : ['resize +5'  , 'expand-window-below']   ,
      \ 'L' : ['<C-W>5>'    , 'expand-window-right']   ,
      \ 'K' : ['resize -5'  , 'expand-window-up']      ,
      \ '=' : ['<C-W>='     , 'balance-window']        ,
      \ 's' : ['<C-W>s'     , 'split-window-below']    ,
      \ 'v' : ['<C-W>v'     , 'split-window-below']    ,
      \ '?' : ['Windows'    , 'fzf-window']            ,
      \ }

let g:which_key_map.f = { '+name' : '+file' }

let g:which_key_map.f.s = ['update', 'save-file']

" vim: set ft=vim :
```
Then trying to type `<Space>f` or `<Space>w`  just leads to

```
SPC f is undefined
SPC w is undefined
```

**Comment by liuchengxu** [comment] 2018-10-05 07:35
You **have to** register `g:which_map_map` otherwise vim-which-key will only use the parsed existing mappings.

```vim
call which_key#register('<Space>', "g:which_key_map")
```

That is to say, vim-which-key will use the output of `:map <leader>` only if you don't register. Since there is no user defined mappings in your provided vimrc, i.e., `:map <leader>` is empty, and you don't register `g:which_key_map` at all, so vim-which-key is aware of nothing and complains nothing is defined.

Please read https://github.com/liuchengxu/vim-which-key#example carefully.

```vim
call which_key#register('<Space>', "g:which_key_map")
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>
```

You've made mistakes in you provided vimrc, try this one:

```vim
runtime! defaults.vim

let mapleader = "\<Space>"

call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-which-key'

call plug#end()

set timeoutlen=500

let g:which_key_map =  {}

call which_key#register('<Space>', "g:which_key_map")
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>

let g:which_key_map.w = {
      \ 'name' : '+windows' ,
      \ 'w' : ['<C-W>w'     , 'other-window']          ,
      \ 'd' : ['<C-W>c'     , 'delete-window']         ,
      \ '-' : ['<C-W>s'     , 'split-window-below']    ,
      \ '|' : ['<C-W>v'     , 'split-window-right']    ,
      \ '2' : ['<C-W>v'     , 'layout-double-columns'] ,
      \ 'h' : ['<C-W>h'     , 'window-left']           ,
      \ 'j' : ['<C-W>j'     , 'window-below']          ,
      \ 'l' : ['<C-W>l'     , 'window-right']          ,
      \ 'k' : ['<C-W>k'     , 'window-up']             ,
      \ 'H' : ['<C-W>5<'    , 'expand-window-left']    ,
      \ 'J' : ['resize +5'  , 'expand-window-below']   ,
      \ 'L' : ['<C-W>5>'    , 'expand-window-right']   ,
      \ 'K' : ['resize -5'  , 'expand-window-up']      ,
      \ '=' : ['<C-W>='     , 'balance-window']        ,
      \ 's' : ['<C-W>s'     , 'split-window-below']    ,
      \ 'v' : ['<C-W>v'     , 'split-window-below']    ,
      \ '?' : ['Windows'    , 'fzf-window']            ,
      \ }

let g:which_key_map.f = { 'name' : '+file' }
let g:which_key_map.f.s = ['update', 'save-file']


" vim: set ft=vim :
```

**Comment by mortang2410** [comment] 2018-10-05 22:42
You are right. I was missing that one line.

**Comment by liuchengxu** [comment] 2018-10-06 00:12
Closing as resolved. Feel free to reopen or file another one if you still have issues.

**Closed by liuchengxu** 2018-10-06 00:12 UTC
Labels: invalid
